# Generated by Django 4.2.16 on 2024-09-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pics'),
        ),
    ]
