# Generated by Django 4.2.16 on 2024-09-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_is_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
