# Generated by Django 4.2.16 on 2024-09-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='verb',
            field=models.CharField(default='overdue task', max_length=255),
        ),
    ]
